### PR TITLE
Hoist configuration from menu item to top-level button for both container and cache

### PR DESCRIPTION
**Pull request by tristantarrant**
imc-configure

### CODE REVIEW

**Comment by pzapata** [comment]
Looks nice, consider using other icon to overuse the pencil, maybe pficon-settings or similar.

**Comment by tristantarrant** [comment]
Done.

**Comment by vblagoje** [comment]
Ok I'll integrate this now @tristantarrant

**Comment by vblagoje** [comment]
Integrated with 533edda Thanks @tristantarrant

**Pull request closed without merging**
