### PR TITLE
ISPN-6934: Refactor the console build system

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-6934

### CODE REVIEW

**Comment by tristantarrant** [comment]
Building this with mvn clean install creates an empty jar

**Comment by ryanemerson** [comment]
@tristantarrant There are a few problems with the build in general, so I am going to work on them and re-push

**Comment by ryanemerson** [comment]
@tristantarrant The build is fixed and we now have minification support, so the resulting jar is approximately half the size as before. I have also fixed various problems with images not being loaded and file translations should work as expected  now.

**Comment by ryanemerson** [comment]
@vblagoje This should only be merged if we don't go down the Typescript route, as the build process changes if we do.

**Comment by ryanemerson** [comment]
Closing as the TypeScript refactor makes this redundant.

**Pull request closed without merging**
