### PR TITLE
Implement patternfly login spinner

### PR DESCRIPTION
**Pull request by vblagoje**
Login spinner implementation. Please review @tristantarrant

### CODE REVIEW

**Comment by tristantarrant** [comment]
Still not happy with how this looks (sorry for the pickiness).
Here's the ideal implementation:
- the user fills in user/password and clicks on the Login button
- the button is disabled and a spinner appears to the left of it
- on a failed login, the login button is re-enabled and an error message is displayed in place of the spinner
- on a successful login, the view switches to the main view (container list), which should however remain covered with a centered spinner until all data is availble

**Comment by vblagoje** [comment]
No problem @tristantarrant . I have already implemented parts of this. Will have it ready soon

**Comment by vblagoje** [comment]
Not the most briliant HTML UI code but I hope it will serve for now until we polish it even further. HAve a look @tristantarrant

**Comment by vblagoje** [comment]
Superceded by https://github.com/infinispan/infinispan-management-console/pull/19

**Pull request closed without merging**
