### PR TITLE
Enable cache creation from templates

### PR DESCRIPTION
**Pull request by vblagoje**
First pass to enable cache creation from templates. Next step is to create cache templates from UI.

### CODE REVIEW

**Comment by vblagoje** [comment]
@tristantarrant Have a look. We have to talk about cache template creation now.

**Comment by tristantarrant** [comment]
Looks good @vblagoje . For completeness, could you please grey out any menu entries that are not connected to actions ?

**Comment by tristantarrant** [comment]
Logout also does not bring me back to the login screen

**Comment by vblagoje** [comment]
Ok @tristantarrant will do so tomorrow morning. Thanks for your review.

**Comment by vblagoje** [comment]
@tristantarrant updated. Have a quick look please.

**Comment by tristantarrant** [comment]
merged, thanks @vblagoje

**Pull request merged**
