### PR TITLE
ISPN-7310: Make Console Use Digest Authentication.

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-7310

@vblagoje I haven't had a chance to check this with IE yet, however it does work with Chrome and Firefox on Fedora.

### CODE REVIEW

**Comment by vblagoje** [comment]
@ryanemerson reload does not work with digest addition :-(

**Comment by vblagoje** [comment]
@ryanemerson apologies. When I do cmd+R (reload on mac) for the containers page - it works. However, it does not work for any other page/view we have. I either get the blank white screen or the screen below
screen shot 2016-12-13 at 5 49 38 am

**Comment by vblagoje** [comment]
And this "reload issue" happens on Firefox, Chrome and Opera. Did not turn on my VirtualBox and IE yet :-)

**Comment by ryanemerson** [comment]
@vblagoje Argh I see, I'm getting similar behaviour on some screens. I'll look into it now

**Comment by vblagoje** [comment]
Good news @ryanemerson IE 11 seems to work really good. Even the errors where new caches, configuration templates did not show up upon adding them - seem to work. I found one error so far though. Upon loggin out I get this screen.
screen shot 2016-12-13 at 6 09 16 am

**Comment by ryanemerson** [comment]
@vblagoje Awesome :). I think the reason logout isn't working is because of the way I force the app to reload by using windows.href. 

I spoke to @tristantarrant earlier and we've decided to add a splash screen, as an entry point to the user, which will have the branding etc and a login button. Once the login button is clicked, the first request to the server will be initiated and the browser login prompt will appear and then when the user clicks logout they will be returned to the splash screen.  So I will incorporate ^ changes into this PR and hopefully that will remove the need to use windows.href and those IE issues.

**Comment by vblagoje** [comment]
Awesome @ryanemerson , keep me in the loop. In the meantime, I will download and install more IE versions and make sure everything is ready to go for IE support!

**Comment by vblagoje** [comment]
@ryanemerson IE10 works as well. No problems noticed other than the logout issue already described

**Comment by ryanemerson** [comment]
@vblagoje The latest commit will hopefully have resolved the refresh issue. I will push another commit to this PR with the welcome splash screen

**Comment by vblagoje** [comment]
Integrated with 948b1bd Great work @ryanemerson

**Pull request closed without merging**
