### PR TITLE
ISPN-6502: Disable editing cache type.

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-6502

### CODE REVIEW

**Comment by vblagoje** [comment]
@ryanemerson we need https://github.com/infinispan/infinispan-management-console/pull/87 integrated before this one. Also, note that when creating a new cache with "none" template we need to allow user to change configuration template type. For all other cases we need to forbid. See if you can adapt this PR to fit that requirement.

**Comment by ryanemerson** [comment]
@vblagoje Disabling changes to template type shouldn't be a problem.  I have noticed that my current solution disables selecting  a cache type on the create cache screen, so I will need to make further changes.

**Comment by vblagoje** [comment]
@ryanemerson ok, let me know when this one is ready for testing and a review!

**Comment by ryanemerson** [comment]
@vblagoje I have pushed a new solution. Note that this is very different to before.

**Comment by vblagoje** [comment]
Thanks @ryanemerson Integrated with 18d59960ceb80c6fcf23c3a510220192874f4645

**Pull request closed without merging**
