### PR TITLE
ISPN-6807 Customization of console features by configuration

### PR DESCRIPTION
**Pull request by vblagoje**
Master only. Work in progress.

### CODE REVIEW

**Comment by vblagoje** [comment]
@ryanemerson updated to use env.js that we can simply drop in the community and product build and satisfy requirements of ISPN-6807

**Comment by ryanemerson** [comment]
@vblagoje We need to re-work this for the Typescript branch

**Comment by vblagoje** [comment]
Right @ryanemerson . Will do so next week.

**Comment by vblagoje** [comment]
Integrated with 8432ee4c9e6cb02bdd47053435a9a2b761bd6b40

**Pull request closed without merging**
