### PR TITLE
ISPN-5234 Search node/cache as you type (on cluster view)

### PR DESCRIPTION
**Pull request by tsykora**
ISPN-5234:Implemented functionality for single cluster view page (P1).

Covered features: 
Search node (search as you type)
Search cache (search as you type)

### CODE REVIEW

**Comment by vblagoje** [comment]
@tsykora it seems that filtering can be done on objects [1] so we don't have to use extra arrays! I'll try to implement this tomorrow unless you want to. Let me know by tomorrow morning (March 26th). 

[1] http://onoffswitch.net/filter-deep-object-properties-angularjs/

**Comment by tsykora** [comment]
@vblagoje oh, nice, thanks! I will fix it today or tomorrow. That's really good that we can avoid another side-array.

**Comment by vblagoje** [comment]
Awesome, I already completed metric node and cache filtering. Let's gather everything and combine it into a PR or series of PRs.

**Comment by tsykora** [comment]
That's cool progress!! I also got familiar with writing end-to-end tests for our code. I will start adding tests as time goes by... this will help us in the future when we will have more features ready and we will not be able to click through all of pages before issuing PR.

Now I vote for a series of PRs where every PR introduces only a "small" bunch of related features.

**Comment by vblagoje** [comment]
@tsykora due to deadlines we have to meet please let me know if you run into some trouble. The article above should help and if we get stuck I will call in the cavalry :-)

**Comment by vblagoje** [comment]
Ok, I also think that makes sense (multiple PRs). Have fun coding :-)

**Comment by tsykora** [comment]
I have implemented custom filter that works exactly as we need to.
I will amend PR tomorrow.

**Comment by tsykora** [comment]
Force-pushed now. 
Introducing custom property filter with minimal impact on our code.

**Comment by vblagoje** [comment]
Will close this one @tsykora as it is superseded by https://github.com/infinispan/infinispan-management-console/pull/9

**Comment by tsykora** [comment]
Closing.

**Pull request closed without merging**
