### PR TITLE
Cumulative updates (ISPN-5773 and other tweaks)

### PR DESCRIPTION
**Pull request by vblagoje**
Master only. @tristantarrant please review.

### CODE REVIEW

**Comment by vblagoje** [comment]
ok @tristantarrant will do. I thought of that too but then we had refresh already in dropdown! It is a good indicator we both intended to do the same thing with refresh :-)

**Comment by tristantarrant** [comment]
I have updated the mockup: https://rawgit.com/infinispan/infinispan-console-mockup/refresh/cache-container-caches.html
Note the use of lowercase. Obviously it needs to be applied to all of the screens

**Comment by vblagoje** [comment]
@tristantarrant please have a look again. Cheers!

**Comment by tristantarrant** [comment]
Rename ACTIONS to Actions

**Comment by vblagoje** [comment]
Right @tristantarrant , I'll remove that commit until I figure out how to resolve that.

**Comment by vblagoje** [comment]
Ok renamed to Actions and removed retrieval of productName and productVersion

**Comment by tristantarrant** [comment]
Pushed.

**Pull request closed without merging**
