### PR TITLE
ISPN-6781 Add support for i18n

### PR DESCRIPTION
**Pull request by vblagoje**
Master only. Please review before we complete all i18n work for English.

### CODE REVIEW

**Comment by ryanemerson** [comment]
@vblagoje Great stuff, this all looks good to me with everything being displayed and working as expected. However, I did notice that none of the edit cache/template screens seem to have been affected, should we not translate the side bars at least?

It might be worth us integrating this PR before the others, so that we can rebase the other PRs and make sure they use translations where possible.

**Comment by vblagoje** [comment]
Ah too late now @ryanemerson Let me rebase it now! And then again please have a look if I missed something

**Comment by vblagoje** [comment]
@ryanemerson rebasing seems to have worked. Have a look now again and feel free to add translations if I have missed some.

**Comment by ryanemerson** [comment]
@vblagoje Integrated c39cb3fddf4fa9f20fe0eb9e89077f72ab7e6b36, thanks!

**Pull request closed without merging**
