### PR TITLE
Add coordinator/view and display it

### PR DESCRIPTION
**Pull request by vblagoje**
Master only. Please review @tristantarrant and @pzapataf

### CODE REVIEW

**Comment by tristantarrant** [comment]
This is good, but you should also show that a node is coordinator on the node detail page.

**Comment by vblagoje** [comment]
Aha, ok @tristantarrant letme fix that and I'll notify you when it is ready!

**Comment by vblagoje** [comment]
Hmm, @tristantarrant you are referring to https://rawgit.com/infinispan/infinispan-console-mockup/master/node-status.html , right? Where should we put the coordinator label?

**Comment by tristantarrant** [comment]
Maybe after the node name:

RUNNING master/server-one (coordinator) IP: 127.0.0.1 - 0 entries

**Comment by vblagoje** [comment]
Ok, awesome. Will do @tristantarrant !

**Comment by vblagoje** [comment]
Done and done @tristantarrant Have a look when you get a chance. Much appreciated!

**Comment by vblagoje** [comment]
Some screenshots:

screen shot 2016-02-18 at 12 26 56 pm
screen shot 2016-02-18 at 12 27 05 pm

**Comment by vblagoje** [comment]
@tristantarrant rebased to latest master

**Comment by tristantarrant** [comment]
Pushed, thanks

**Pull request closed without merging**
