### PR TITLE
ISPN-7331 Removing task before undeploying it should show an error

### PR DESCRIPTION
**Pull request by vblagoje**
Master only. Resolves https://issues.jboss.org/browse/ISPN-7331 in an even better and simpler way than suggested. We enable/disable remove button in appropriate states. Please review @ryanemerson

### CODE REVIEW

**Comment by ryanemerson** [comment]
@vblagoje I'm unable to test this at the minute as I am receiving the following error when trying to upload a deployment:

```javascript
POST http://localhost:3000/management-upload 415 (Unsupported Media Type)
(anonymous) @ angular.js:12014
sendReq @ angular.js:11779
serverRequest @ angular.js:11574
processQueue @ angular.js:16386
(anonymous) @ angular.js:16402
$eval @ angular.js:17685
$digest @ angular.js:17498
$apply @ angular.js:17793
(anonymous) @ angular.js:25893
dispatch @ jquery.js:4435
elemData.handle @ jquery.js:4121

DmrService.ts:170 An unspecified error has been received from the server
AddDeploymentModalCtrl.ts:16 Error in deployment upload of [object File]:An unspecified error has been received from the server
```

Is this the regression you referenced in your email?

**Comment by vblagoje** [comment]
Yes @ryanemerson that what I experienced as well. Roll back your git tree to before digest and you'll see that everything works ok. Something went wrong somehow in that digest commit :-(

**Comment by vblagoje** [comment]
@ryanemerson I tested it by downloading beta server build, using its console, uploading a deployment and then testing how this works from standard dev env

**Comment by ryanemerson** [comment]
@vblagoje Integrated and I have created as it is a separate issue. FYI, you can deploy to the server via the CLI using `deploy <local jar path> --all-server-groups`

**Pull request merged**
