### PR TITLE
ISPN-6264 Reorganize cache configuration screens

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-6264

### CODE REVIEW

**Comment by vblagoje** [comment]
Impressive @tristantarrant Power of angular directives at its best.

**Comment by tristantarrant** [comment]
@vblagoje removed the $log

**Comment by vblagoje** [comment]
Ok @tristantarrant , I will take a look and integrate it after lunch! I don't think there are any potential conflicts between your PR and mine.

**Comment by vblagoje** [comment]
@tristantarrant the changes screwed up a bit the cache configuration screens. See attachement
screen shot 2016-02-25 at 1 56 13 pm

**Comment by vblagoje** [comment]
Integrated with 8a703ff Thanks @tristantarrant

**Pull request closed without merging**
