### PR TITLE
ISPN-9337 Lock admin console dependencies

### PR DESCRIPTION
**Pull request by vblagoje**
Lockdown dependencies for 9.2.x

### CODE REVIEW

**Comment by ryanemerson** [comment]
How come this only affects `package.json`, but https://github.com/infinispan/infinispan-management-console/pull/256/files also changes `jspm.conf`. I think both files need updating right?

**Comment by vblagoje** [comment]
It does, I also notice that and was confused as well. I also di gulp clean
dist and jspm.conf.js did not change. Weird. I'll try once again

**Comment by vblagoje** [comment]
@ryanemerson Fixed, I removed all node_modules and vendor/jspm_packages and full rebuild created a new jspm.conf.js file. Will do it once again for 9.3.x branch just in case I messed up something the first time.

**Comment by vblagoje** [comment]
@ryanemerson this one should be ready to get into 9.2.x now

**Comment by ryanemerson** [comment]
Thanks

**Pull request merged**
