### PR TITLE
ISPN-6782 : Add connectivity lost warning message

### PR DESCRIPTION
**Pull request by vblagoje**
Master only. See https://issues.jboss.org/browse/ISPN-6782 for more details

### CODE REVIEW

**Comment by ryanemerson** [comment]
@vblagoje This doesn't appear to work for me. I don't see any warning messages after killing the server and 1) waiting indefinitely for an error message, or 2) clicking on a new page within the console.

**Comment by vblagoje** [comment]
Ok @ryanemerson Checking

**Comment by vblagoje** [comment]
@ryanemerson have a look again.

**Comment by ryanemerson** [comment]
@vblagoje Integrated https://github.com/infinispan/infinispan-management-console/commit/1d2462d5537eaf6ca1de1f23fe5c10b8fecb03a9, thanks

**Pull request closed without merging**
