### PR TITLE
ISPN-9256 Upgrade npm dependencies

### PR DESCRIPTION
**Pull request by vblagoje**
Carefully review at your leisure moment @ryanemerson I tried 'mvn install' on my fedora laptop from scratch and it worked. No rush to integrate but we should upgrade at the appropriate moment in dev cycle.

### CODE REVIEW

**Comment by ryanemerson** [comment]
@vblagoje I don't think package-lock.json should be committed. +10,998 lines :fearful:

**Comment by vblagoje** [comment]
I know @ryanemerson I thought so too, but the build recommends it to be [committed](https://docs.npmjs.com/files/package-lock.json).

**Comment by ryanemerson** [comment]
@vblagoje Ok, good to know, I didn't realise that. I think you need to rebase this PR on the version changes in master. When I run `mvn clean install` it completes, however `src/jspm.conf.js` and `package-lock.json` change. Furthermore, angular does not seem to load and I just get a blank screen in the browser. I think this is because of your changes to `build-dist.js`, not sure why they are necessary?

**Comment by vblagoje** [comment]
Ok, let me look at that. Maybe I've messed up something. Either way lets
integrate this one in new master only after we branch 9.3.x

**Comment by ryanemerson** [comment]
@vblagoje Already branched, see comments on Zulip

**Comment by vblagoje** [comment]
@ryanemerson see the change in build-dist.js, the old way of building would not work any more after jspm upgrade. If you can figure out how to make the old way work that would be great. I could not. There were also some weird warning with Typescript update. Hmmm, let me investigate a bit more how can we make this change more robust. I would also like to understand better what is going on. I'll get back to you on this one

**Comment by vblagoje** [comment]
@ryanemerson I've verified that the app works in all screens. There were some issues with patternfly tabs so I locked them to the same versions as in 9.3.x branch. If you delete node, node_modules, vendor/jspm_packages and do a full mvn clean install - it should work.

**Comment by ryanemerson** [comment]
@vblagoje the console is not loading with `gulp serve:dist`, I am getting "error TS2503: Cannot find namespace 'ng'." for all ts files pretty much. Also, `src/jspm.conf.js` is still changing after executing `mvn clean install`.

**Comment by vblagoje** [comment]
Ok @ryanemerson ...looking into it

**Comment by vblagoje** [comment]
@ryanemerson I don't get the typescript problem but serving from dist does not work. Investigating

**Comment by vblagoje** [comment]
When you get a chance see how this works for you now @ryanemerson  Don't forget to erase node_modules, typings etc. I use rm -rf typings/ vendor/jspm_packages/ node_modules/ node/

**Comment by ryanemerson** [comment]
@vblagoje It is loading as expected although `src/jspm.conf.js` always changes after a `mvn clean install` build resulting in an unclean git repo. 

Also, the following warnings are output during compilation:

```javascript
src/components/directives/VertilizeContainerDirective.ts(14,3): error TS2416: Property 'controller' in type 'VertilizeContainerDirective' is not assignable to the same property in base type 'IDirective<IScope>'.
  Type 'Function' is not assignable to type 'string | (new (...args: any[]) => IController) | ((...args: any[]) => void | IController) | (stri...'.
    Type 'Function' is not assignable to type '(string | (new (...args: any[]) => IController) | ((...args: any[]) => void | IController))[]'.
      Property 'push' is missing in type 'Function'.

src/components/directives/VertilizeContainerDirective.ts(19,9): error TS2322: Type '($window: IWindowService) => VertilizeContainerDirective' is not assignable to type 'IDirectiveFactory<IScope>'.
  Type 'VertilizeContainerDirective' is not assignable to type 'IDirective<IScope> | IDirectiveLinkFn<IScope>'.
    Type 'VertilizeContainerDirective' is not assignable to type 'IDirectiveLinkFn<IScope>'.
      Type 'VertilizeContainerDirective' provides no match for the signature '(scope: IScope, instanceElement: JQLite, instanceAttributes: IAttributes, controller?: IController | { [key: string]: IController; } | IController[], transclude?: ITranscludeFunction): void'.
src/services/container/ContainerService.ts(210,26): error TS2345: Argument of type 'IPromise<{ "sites-online": any; "sites-offline": any; "sites-mixed": any; }>' is not assignable to parameter of type '{ [id: string]: string[]; } | IPromise<{ [id: string]: string[]; }>'.
  Type 'IPromise<{ "sites-online": any; "sites-offline": any; "sites-mixed": any; }>' is not assignable to type 'IPromise<{ [id: string]: string[]; }>'.
    Type '{ "sites-online": any; "sites-offline": any; "sites-mixed": any; }' is not assignable to type '{ [id: string]: string[]; }'.
      Index signature is missing in type '{ "sites-online": any; "sites-offline": any; "sites-mixed": any; }'.

```

**Comment by vblagoje** [comment]
Yes, I know about these but did not know how to resolve them. Will try one more time :-)

**Comment by vblagoje** [comment]
@ryanemerson I fixed Angular loading twice issue as well as sanitization warning. However, I am not sure how to resolve these compilation errors. The application still works but I'll need your help to fix these errors and they do not seem urgent.

**Comment by vblagoje** [comment]
@ryanemerson I also don't get dirty git - I tried a fresh install on a completely new directory

**Comment by vblagoje** [comment]
I also think we should check other branches for Angular loading twice issue. I'll do that now

**Comment by ryanemerson** [comment]
@vblagoje Remember only 9.3.x is required.

**Comment by ryanemerson** [comment]
@vblagoje Here is this PR, plus the changes to `src/jspm.conf` that I experience. Please checkout the changes locally and try a clean build. If no files change, then we know that my commit can be safely squased with yours.

https://github.com/ryanemerson/infinispan-management-console/tree/vblagoje-t_9256

**Comment by vblagoje** [comment]
@ryanemerson I can't build your branch, it fails with https://gist.github.com/vblagoje/4857ae64f02f27b19ff5087544596224 It seems like the encoding used on your OS is not very much liked by OSX. What shall we do?

**Comment by ryanemerson** [comment]
@vblagoje I don't want to spend any more time on this. I have merged and will just have to undo the changes to `src/jspm.conf`. I fear there may be an underlying issue here that will pop up later

**Pull request merged**
