### PR TITLE
Cumulative updates (ISPN-5766 and ISPN-5764)

### PR DESCRIPTION
**Pull request by vblagoje**
Master only. @tristantarrant please review.

### CODE REVIEW

**Comment by tristantarrant** [comment]
Good job !
A few notes:
* make sure that you match the height of all cards in the cache container and cluster view, including the "add" cards
* the mockup has a "styles.css" for collecting some console-specific styles, including variations to the PF styles. In particular .header-row { margin-bottom: 20px; } which creates some extra breathing space
* some of the cache traits (bounded and remote backup) use a different font because the text is inside the span that puts the icon.

**Comment by vblagoje** [comment]
Ok @tristantarrant will take care of these over the weekend! Thanks

**Comment by vblagoje** [comment]
I did not know how to address "some of the cache traits (bounded and remote backup) use a different font because the text is inside the span that puts the icon". If you know how, please do. Otherwise, we can do it later @tristantarrant

**Comment by tristantarrant** [comment]
Good, one last thing: remove the status/events text. Those are mockups and until we can put stuff there, it's best to leave it blank

**Comment by tristantarrant** [comment]
Pushed, thanks !

**Pull request merged**
