### PR TITLE
ISPN-9337 Lock admin console dependencies

### PR DESCRIPTION
**Pull request by vblagoje**
For 9.3.x branch

### CODE REVIEW

**Comment by vblagoje** [comment]
This one is ok, verified with full rebuild

**Comment by ryanemerson** [comment]
This results in `src/jspm.conf.js` having unstaged changes after the build

**Comment by vblagoje** [comment]
@ryanemerson this does not happen to me. I clean all directories and even after fresh install - there are no changes to src/jspm.conf.js I thought it could be node version related. I built it with two different versions of the node without any issues. Could it be OS platform specific?

**Comment by ryanemerson** [comment]
@vblagoje That comment was 10 days ago ... can you try what I suggested yesterday on https://github.com/infinispan/infinispan-management-console/pull/252 please. I suspect the cause of the dirty git repo is the same.

Also, are we keeping this PR or close in favour of https://github.com/infinispan/infinispan-management-console/pull/258 which also locks the dependencies?

**Comment by vblagoje** [comment]
Yeah, I would just integrate #258 , we can close this one. I'll try it on #252 now

**Pull request closed without merging**
