### PR TITLE
Real boot dialogs, improved cluster page refresh

### PR DESCRIPTION
**Pull request by vblagoje**
Master only. Reworked page refresh on cluster view and node pages related to node starting, stopping, removing as well as adding new nodes. Using real boot dialogs. Please review @pzapataf @tristantarrant and *do not* integrate yet

### CODE REVIEW

**Comment by pzapataf** [comment]
It works much better now. One small tweak I'd do is replace the empty memory usage  chart when a node is stopped by a message 'Node is stopped'.

**Comment by vblagoje** [comment]
@pzapataf fixed the commit log ISPN-6140 reference and included empty memory screen. The message "Node is stopped" looked odd a bit and redundant as well as the red-colored "STOPPED" indicator is already indicating node status. I guess we can polish it further if needed.

**Comment by vblagoje** [comment]
@pzapataf @tristantarrant I added another commit with Pedro's suggestion. Please choose which one you like better, squash and integrate

**Comment by tristantarrant** [comment]
Squashed and pushed. Nice !

**Pull request closed without merging**
