### PR TITLE
fix for wrong attributes in cache-status page

### PR DESCRIPTION
**Pull request by mvrabel**

### CODE REVIEW

**Comment by vblagoje** [comment]
Hey @mvrabel thanks man. Looks solid! I'll test it today and integrate it!

**Comment by mvrabel** [comment]
@vblagoje thanks, but there is one issue with the clusterwide-cache-loader-stores. https://issues.jboss.org/browse/ISPN-6181

**Comment by vblagoje** [comment]
Ok @mvrabel , can we integrate this one before the one is fixed?

**Comment by mvrabel** [comment]
@vblagoje I would say we can integrate it.

**Comment by tristantarrant** [comment]
Pushed, thanks

**Pull request closed without merging**
