### PR TITLE
ISPN-5234 Implement single cluster view page (cluster availability)

### PR DESCRIPTION
**Pull request by vblagoje**
Master only. Cluster availability (based on work of Tomas Sykora)

### CODE REVIEW

**Comment by vblagoje** [comment]
@tristantarrant this PR implements cluster availability - I reworked it based on ideas of Tomas but is more focused and succinct. @tsykora please feel free to take this pull request and change the author of the commit to be your name.

**Comment by tsykora** [comment]
Cool! I see your changes. 
It would be great to have my PR integrated and then "merge" your PR on top of that.

One thing I was thinking about is exactly that Cluster this.availability and this.getAvailability. I have there this.clusterAvailability as it is more descriptive in my oppinion. But I understand that when we are calling getCluster('clustered').availability it is crystal clear that this is availability of a cluster :)

Or how about this @vblagoje I will cherry pick your commit, resolve conflicts a update my PR.

**Comment by tsykora** [comment]
@vblagoje @tristantarrant I cherry picked Vladimir's commit into my branch and refreshed PR (https://github.com/infinispan/infinispan-management-console/pull/5) Now it contains all our weekend changes at one place.

**Comment by vblagoje** [comment]
@tsykora We should have focused PRs. I understand that you want to integrate all these at once but we should focus on our requirements IMHO. Our requirements dictate that we implement cache availability first. Also if we keep PRs focused @tristantarrant can follow our work easier, review and approve integration. I will also get some additional review help from Angular gurus so we can be sure that we are on the right track.

**Comment by tsykora** [comment]
Ok, anything that works for you. 

I will be working on other features in diferent branches and will rebase once we have our current PRs integrated.

**Pull request closed without merging**
