### PR TITLE
ISPN-7185 Confirmation dialog is not displayed when changing configur…

### PR DESCRIPTION
**Pull request by vblagoje**
Master only. Fixes JDG-561 blocker. Please review and integrate @ryanemerson

### CODE REVIEW

**Comment by ryanemerson** [comment]
@vblagoje Should this also apply to changing cache configuration? At the moment this only addresses templates.

**Comment by vblagoje** [comment]
@ryanemerson lets ask Roman Macor

**Comment by rmacor** [comment]
@vblagoje @ryanemerson This should apply to cache configuration as well, actually, in the previous version it didn't apply to templates, but I suppose it's better if it's in both places - looks more consistent. WDYT?

**Comment by ryanemerson** [comment]
@rmacor @vblagoje Personally I think it should be both, as the consequences of changing  a configuration and a template are similar, so it makes sense that there should be the same number of hoops to jump through for each action.

**Comment by vblagoje** [comment]
Updated @ryanemerson Please review and integrate!

**Pull request merged**
