### PR TITLE
ISPN-7085 Add Codemirror editor for editing scripts

### PR DESCRIPTION
**Pull request by vblagoje**
Master branch only. See https://issues.jboss.org/browse/ISPN-7085 for more details @ryanemerson make sure that on your ISPN branch https://github.com/infinispan/infinispan/pull/6000 is integrated

### CODE REVIEW

**Comment by ryanemerson** [comment]
@vblagoje Where is the option to edit tasks in the UI? I might be going blind, but I can't seem to find it.

**Comment by vblagoje** [comment]
@ryanemerson sorry I got distracted with Fedora install. We can not edit admin tasks, you need to create one for yourself and then you can edit it. 
screen shot 2018-05-31 at 1 05 36 pm

**Comment by vblagoje** [comment]
@ryanemerson what do you say if you are happy with this one - we could release today?

**Comment by ryanemerson** [comment]
@vblagoje Sorry for the delay

**Pull request merged**
